[package]
name = "cargo-config"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
miette = { version = "7.2.0", features = ["fancy"] }
owo-colors = "4.0.0"
simple-home-dir = "0.3.2"
which = "6.0.1"
